baseurl = "http://glennryan.info/"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "en-us"
title = "glenn ryan"
theme = "hugo-hikari-theme"
# Shown in the side menu
copyright = "&copy; Glenn Ryan 2016. All rights reserved."
canonifyurls = true
googleAnalytics = "UA-74357056-1"
disqusShortname = "glennryan"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
  # Shown in the home page
  name = "Glenn Ryan"
  subtitle = "Sharing learnings and discoveries"
  brand = "hikari"
  copyright = "POWERED BY [HUGO](//gohugo.io) - THEME: [HIKARI](//github.com/digitalcraftsman/hugo-hikari-theme) - © GLENN RYAN"
  # CSS name for highlight.js
  pageNotFoundTitle = "Page not found"
  pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Hi, I'm Glenn"
	bio = "I'm an embedded C software engineer trying to keep my algorithmic toolbox sharp and my developer skillset even sharper. I write about it here."
	subscribe = "Subscribe"
	followme = "Find me on"
    avatar = "static/img/me.jpg"

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/gbr"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "//twitter.com/bgarryan"

	[[params.offcanvas.socialnetworks]]
		name = "LinkedIn"
		url = "//linkedin.com/gbryan"
